### PR TITLE
Add lxqt-build-tools

### PR DESCRIPTION
**Pull request by pmattern**
Should be pretty obvious.

Sending as PR as still not 100% sure about that submodule battle. (Checkout was compiling flawlessly here, though.)

### CODE REVIEW

**Comment by pmattern** [comment]
`build_all_cmake_projects.sh` is covered by this PR. Or what do you mean by "build scripts"?

**Comment by paulolieuthier** [comment]
@pmattern you forgot the main CMakeLists.txt file ("super build" mode). Besides that, GTM.

> Sending as PR as still not 100% sure about that submodule battle.

For this kind of thing there must always be a PR.

**Comment by pmattern** [comment]
> you forgot the main CMakeLists.txt file ("super build" mode)
 
True, but there seem to be some flaws regarding CMake anyway.
libfm-qt, qtermwidget, qterminal and pavucontrol-qt are missing as well. Also, invoking cmake the usual way fails right now even when a line `add_subdirectory(lxqt-build-tools)` is added as lxqt-build-tools aren't found.
So shouldn't we address all those CMake woes in an issue or PR on its own once this one has been dealt with?

**Comment by paulolieuthier** [comment]
Fair enough.

**Comment by luis-pereira** [comment]
@pmattern superbuild mode support PR [here](https://github.com/lxde/lxqt/issues/1172#issuecomment-254337744).

**Pull request merged**
